apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: r8y5uve6u-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-9a9f60bc25.u9mk.p3.openshiftapps.com/rhtap/rhtap-qe:367a5ed1dc7df15e4c528e1a2e7679b0e7bb1890@sha256:484ea9262a9a0128cadb773ff3b20f2fba78aba173133de58eda1086ddd2658a
          name: container-image
